package com.example.movieappcleanarchitecture

import android.app.Application
import com.example.movieappcleanarchitecture.di.AppComponent
import com.example.movieappcleanarchitecture.di.DaggerAppComponent

/**
 * Application class — the entry point of the app.
 *
 * Creates the Dagger Component at app startup so dependencies
 * are available before any screen is shown.
 *
 * COMPARISON WITH MANUAL DI:
 *
 *   Manual DI:                              Dagger DI:
 *   appContainer = AppContainer(this)       appComponent = DaggerAppComponent.factory().create(this)
 *
 * DaggerAppComponent is auto-generated by Dagger after you build the project.
 * It implements AppComponent interface and knows how to create all dependencies
 * using the @Provides methods in AppModule.
 *
 * NOTE: DaggerAppComponent will show as red/unresolved until you build the project.
 * This is normal — Dagger generates this class during compilation.
 */
class MovieApplication : Application() {

    lateinit var appComponent: AppComponent

    override fun onCreate() {
        super.onCreate()
        appComponent = DaggerAppComponent.factory().create(this)
    }
}
